#pragma once

#ifdef CPSM_BUILD_AS_MOCKUP
#undef CPSM_BUILD_AS_MOCKUP
#endif

#define CPSM_BUILD_AS_MOCKUP

#ifdef MAIN_PROJECT_VERSIONING_MAJOR
#undef MAIN_PROJECT_VERSIONING_MAJOR
#endif
#ifdef MAIN_PROJECT_VERSIONING_MINOR
#undef MAIN_PROJECT_VERSIONING_MINOR
#endif
#ifdef MAIN_PROJECT_VERSIONING_PATCH
#undef MAIN_PROJECT_VERSIONING_PATCH
#endif

#define MAIN_PROJECT_VERSIONING_MAJOR 1
#define MAIN_PROJECT_VERSIONING_MINOR 0
#define MAIN_PROJECT_VERSIONING_PATCH 1

#ifdef PROJECT_GITHUB_RELEASE_DEFINE
#undef PROJECT_GITHUB_RELEASE_DEFINE
#endif
#define PROJECT_GITHUB_RELEASE_DEFINE "https://api.github.com/repos/mathieu0c/CPSMPlongees/releases/latest"
